{"name": "test_complete_todos[item_list0]", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL\nCall log:\n  - navigating to \"/\", waiting until \"load\"", "trace": "page = <Page url='about:blank'>\n\n    @pytest.fixture\n    def todo_page(page):\n        \"\"\"Todo Page object with navigation already done.\"\"\"\n        todo = TodoPage(page)\n>       todo.navigate()\n\n../conftest.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../pages/todo_page.py:15: in navigate\n    self.page.goto(\"/\")\n../.venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py:9019: in goto\n    self._sync(\n../.venv/lib/python3.9/site-packages/playwright/_impl/_page.py:556: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n../.venv/lib/python3.9/site-packages/playwright/_impl/_frame.py:153: in goto\n    await self._channel.send(\n../.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py:69: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x101cb7640>\ncb = <function Channel.send.<locals>.<lambda> at 0x10397b820>\nis_internal = False, title = None\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(\n            task, \"__pw_stack__\", None\n        ) or inspect.stack(0)\n    \n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: Page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL\nE           Call log:\nE             - navigating to \"/\", waiting until \"load\"\n\n../.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py:558: Error"}, "parameters": [{"name": "item_list", "value": "['Task 1', 'Task 2', 'Task 3']"}], "start": 1755569149321, "stop": 1755569149321, "uuid": "90219f15-be2c-45b6-b7b2-3648d5c231ce", "historyId": "7ec1e55eb00a3cb43bb759fcd7b32f3d", "testCaseId": "628791a840c3c30d2e93fbafdb641cc9", "fullName": "tests.test_todos.TestTodos#test_complete_todos", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_todos"}, {"name": "subSuite", "value": "TestTodos"}, {"name": "host", "value": "Matthews-MacBook-Air.local"}, {"name": "thread", "value": "31360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_todos"}], "titlePath": ["tests", "test_todos.py", "TestTodos"]}