{"uuid": "553219e3-878e-4644-850e-d008fe430555", "children": ["8267746c-f9c3-426f-93b0-fecc4f02f0b9"], "befores": [{"name": "todo_page", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL\nCall log:\n  - navigating to \"/\", waiting until \"load\"\n\n", "trace": "  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/conftest.py\", line 22, in todo_page\n    todo.navigate()\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/pages/todo_page.py\", line 14, in navigate\n    self.page.goto(\"/\")\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py\", line 9019, in goto\n    self._sync(\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_page.py\", line 556, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_frame.py\", line 153, in goto\n    await self._channel.send(\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py\", line 69, in send\n    return await self._connection.wrap_api_call(\n  File \"/Users/matthewchoi/Desktop/Work/python-playwright-demo/.venv/lib/python3.9/site-packages/playwright/_impl/_connection.py\", line 558, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1755569473471, "stop": 1755569473472}], "start": 1755569473471, "stop": 1755569473578}